### ISSUE TITLE
IllegalStateException in BellRepeater.stop()

### ISSUE THREAD

**Issue by czlee** [czlee/debatekeeper-old#8]
When a scheduled bell rings at about the same time as a user-pressed bell rings, an `IllegalStateException` occurs when trying to stop the `MediaPlayer` in `BellRepeater`.

This is intermittently reproducible by pressing the "Bell" button (in a non-silent mode) repeatedly just before/through a scheduled bell (including an overtime bell).

It may be caused by the scheduled bell's taking execution to stop the currently-playing bell, interrupting the user-pressed bell while it is also in the process of stopping the last one, _after_ the user-pressed bell stopped the last bell (in preparation to play a new one) but _before_ execution reaches the line where `mMediaPlayer` (member of `BellRepeater`) is set to `null`.

Stack trace:

```
java.lang.IllegalStateException
at android.media.MediaPlayer._stop(Native Method)
at android.media.MediaPlayer.stop(MediaPlayer.java:1100)
at net.czlee.debatekeeper.BellRepeater.stop(BellRepeater.java:187)
at net.czlee.debatekeeper.AlertManager.playBell(AlertManager.java:214)
at net.czlee.debatekeeper.SpeechManager.doOvertimeBell(SpeechManager.java:392)
at net.czlee.debatekeeper.SpeechManager.access$3(SpeechManager.java:390)
at net.czlee.debatekeeper.SpeechManager$IncrementTimeTask.run(SpeechManager.java:96)
at java.util.Timer$TimerImpl.run(Timer.java:284)
```

or:

```
java.lang.IllegalStateException
at android.media.MediaPlayer._stop(Native Method)
at android.media.MediaPlayer.stop(MediaPlayer.java:1108)
at net.czlee.debatekeeper.BellRepeater.stop(BellRepeater.java:187)
at net.czlee.debatekeeper.AlertManager.playBell(AlertManager.java:214)
at net.czlee.debatekeeper.AlertManager.triggerAlert(AlertManager.java:284)
at net.czlee.debatekeeper.SpeechManager.handleBell(SpeechManager.java:355)
at net.czlee.debatekeeper.SpeechManager.access$1(SpeechManager.java:350)
at net.czlee.debatekeeper.SpeechManager$IncrementTimeTask.run(SpeechManager.java:92)
at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by nujnay** [comment]
thx
